[package]
name = "optick-rs"
version = "1.1.3"
authors = ["Vadim Slyusarev <vadim@optick.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
